main/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.decorators.cache import cache_page

from accounts.views import StudentMainPageView, StudentCourseListView, StudentCourseDetailView
from courses.views import ManageCourseListView, CourseCreateView, CourseDeleteView, CourseUpdateView, \
    CourseModuleUpdateView, ContentCreateUpdateView, ContentDeleteView, ModuleContentListView, SubjectListView, \
    CourseListView, CourseDetailView, enroll_to_course, un_enroll_from_course, ModuleOrderView, ContentOrderView
from main import settings
from question_bank.views import ManageQuestionBankListView, QuestionBankDeleteView, \
    QuestionBankListView, QuestionBankDetailView, QuestionBankCreateView, \
    QuestionBankUpdateView, QuestionBankContentCreateUpdateView, QuestionBankManagerView, QuestionBankContentDeleteView, \
    generate_question, QuestionBankGeneratorFormView
from quiz.views import QuizManageListView, QuizCreateUpdateView, QuizContentDeleteView, StudentQuizStartView, QuizTake, \
    QuizUserProgressView, QuizMarkingList, QuizMarkingDetail, QuizResults

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),

    path('', StudentMainPageView.as_view(), name='student_main_page'),

    path('courses/', include([
        path('mine/', ManageCourseListView.as_view(), name='manage_course_list'),
        path('create/', CourseCreateView.as_view(), name='course_create'),
        path('<pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
        path('<pk>/edit/', CourseUpdateView.as_view(), name='course_edit'),

        path('<pk>/module/', CourseModuleUpdateView.as_view(), name='course_module_update'),
        path('module/<int:module_id>/content/<model_name>/create/', ContentCreateUpdateView.as_view(),
             name='module_content_create'),
        path('module/<int:module_id>/content/<model_name>/<id>/', ContentCreateUpdateView.as_view(),
             name='module_content_update'),
        path('content/<int:id>/delete/', ContentDeleteView.as_view(), name='module_content_delete'),
        path('module/<int:module_id>/', ModuleContentListView.as_view(), name='module_content_list'),

        path('subject/', SubjectListView.as_view(), name='subject_list'),
        path('subject/<slug:subject>/', CourseListView.as_view(), name='course_list_subject'),
        path('<slug:slug>/', CourseDetailView.as_view(), name='course_detail'),

        path('ajax/', include([

            path('module/order/', ModuleOrderView.as_view(), name='module_order'),
            path('content/order/', ContentOrderView.as_view(), name='content_order'),
            path('enroll/to/course/', enroll_to_course, name='enroll_to_course'),
            path('un/enroll/from/course/', un_enroll_from_course, name='un_enroll_from_course'),
        ])),
    ])),

    path('quiz/', include([
        path('manager/', include([
            path('progress/', QuizUserProgressView.as_view(), name='quiz_progress'),
            path('marking/', QuizMarkingList.as_view(), name='quiz_marking'),
            path('marking/<int:pk>/', QuizMarkingDetail.as_view(), name='quiz_marking_detail'),
            path('<slug:slug>/', QuizManageListView.as_view(), name='question_list_manager'),
            path('<slug:slug>/content/<model_name>/create/', QuizCreateUpdateView.as_view(),
                 name='quiz_content_create'),
            path('<slug:slug>/content/<model_name>/<int:id>/update/', QuizCreateUpdateView.as_view(),
                 name='quiz_content_update'),
            path('<int:pk>/delete/', QuizContentDeleteView.as_view(), name='quiz_content_delete'),
        ])),
    ])),

    path('question-bank/', include([
        path('', QuestionBankListView.as_view(), name='question_bank_list'),
        path('<int:pk>/', QuestionBankDetailView.as_view(), name='question_bank_detail'),

        path('manage/', include([
            path('mine/', ManageQuestionBankListView.as_view(), name='question_bank_mine'),
            path('create/', QuestionBankCreateView.as_view(), name='question_bank_create'),
            path('<int:pk>/update/', QuestionBankUpdateView.as_view(), name='question_bank_update'),
            path('<int:pk>/delete/', QuestionBankDeleteView.as_view(), name='question_bank_delete'),

            path('<int:pk>/manager/', QuestionBankManagerView.as_view(), name='question_bank_manager'),
            path('<int:pk>/content/', include([
                path('generate/question/bank/', QuestionBankGeneratorFormView.as_view(), name='generate_question_bank'),
                path('generate/question/', generate_question, name='generate_question'),
                path('<model_name>/create/', QuestionBankContentCreateUpdateView.as_view(),
                     name='question_bank_content_create'),
                path('<model_name>/<int:content_id>/update/', QuestionBankContentCreateUpdateView.as_view(),
                     name='question_bank_content_update'),
                path('<int:content_id>/delete/', QuestionBankContentDeleteView.as_view(),
                     name='question_bank_content_delete'),
            ]))
        ])),

    ])),

    path('account/', include([
        path('main/', StudentMainPageView.as_view(), name='student_main_page'),
        path('courses/', StudentCourseListView.as_view(), name='student_course_list'),
        path('course/<pk>/', cache_page(60 * 15)(StudentCourseDetailView.as_view()), name='student_course_detail'),
        path('course/<pk>/<module_id>/', cache_page(60 * 15)(StudentCourseDetailView.as_view()),
             name='student_course_detail_module'),
        path('quiz/<slug:slug>/', StudentQuizStartView.as_view(), name='quiz_start'),
        path('quiz/<slug:slug>/take/<int:question_index>/', QuizTake.as_view(), name='quiz_start'),
        path('quiz/<slug:slug>/results/', QuizResults.as_view(), name='quiz_results'),
    ])),

    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MaxValueValidator
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from common.models import TimestampAbstractModel
from common.utils import generate_filename
from courses.fields import OrderField
from accounts.models import User


class Subject(MPTTModel, TimestampAbstractModel):
    class Meta:
        verbose_name_plural = _('Subjects')
        verbose_name = _('Subject')
        ordering = ['title']

    title = models.CharField(max_length=200, verbose_name=_('Title'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name='SLUG')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            verbose_name=_('Parent'))

    def get_absolute_url(self):
        return reverse('course_list_subject', kwargs={'subject': self.slug})

    def __str__(self):
        return self.title


class Course(TimestampAbstractModel):
    class Meta:
        verbose_name_plural = _('Courses')
        verbose_name = _('Course')

    owner = models.ForeignKey(to='accounts.User', null=True, blank=False, on_delete=models.SET_NULL,
                              related_name='courses_created', verbose_name=_('Owner'))
    subject = models.ForeignKey(to='Subject', null=True, blank=False, on_delete=models.SET_NULL, related_name='course',
                                verbose_name=_('subject'))
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    slug = models.SlugField(max_length=255, unique=True, verbose_name='SLUG')
    description = models.TextField(verbose_name=_('Description'))
    image = models.FileField(upload_to=generate_filename, verbose_name=_('Image'))
    students = models.ManyToManyField(to='accounts.User',
                                      related_name='courses_joined',
                                      blank=True,
                                      verbose_name=_('Students'))
    enrollment_key = models.CharField(max_length=128, null=True, blank=True, verbose_name=_('Enrollment Key'))
    is_deleted = models.BooleanField(default=False, verbose_name=_('Is Deleted?'))

    def get_absolute_url(self):
        return reverse('course_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Module(TimestampAbstractModel):
    class Meta:
        verbose_name_plural = _('Module')
        verbose_name = _('Module')
        ordering = ['order']

    course = models.ForeignKey(to='Course', related_name='module', on_delete=models.CASCADE, verbose_name=_('Course'))
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    order = OrderField(blank=True, for_fields=['course'])

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)


class Content(TimestampAbstractModel):
    class Meta:
        verbose_name_plural = _('Content')
        verbose_name = _('Content')
        ordering = ['order']

    TEXT = 'text'
    VIDEO = 'video'
    IMAGE = 'image'
    FILE = 'file'
    QUIZ = 'quiz'

    CONTENT_TYPE_LIST = [TEXT, VIDEO, IMAGE, FILE, QUIZ]

    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE,
                               verbose_name=_('Module'))
    content_type = models.ForeignKey(ContentType,
                                     limit_choices_to={'model__in': (TEXT,
                                                                     VIDEO,
                                                                     IMAGE,
                                                                     FILE,
                                                                     QUIZ)},
                                     on_delete=models.CASCADE,
                                     verbose_name=_('Content Type'))
    object_id = models.PositiveIntegerField(verbose_name=_('Object id'))
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])


class ItemBase(TimestampAbstractModel):
    owner = models.ForeignKey(User,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE,
                              verbose_name=_('Owner'))
    title = models.CharField(max_length=250, verbose_name=_('Title'))

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('courses/content/{}.html'.format(
            self._meta.model_name), {'item': self})


class Text(ItemBase):
    class Meta:
        verbose_name_plural = _('Text')
        verbose_name = _('Text')

    content = models.TextField(verbose_name=_('Content'))


class File(ItemBase):
    class Meta:
        verbose_name_plural = _('File')
        verbose_name = _('File')

    file = models.FileField(upload_to=generate_filename, verbose_name=_('File'))


class Image(ItemBase):
    class Meta:
        verbose_name_plural = _('Image')
        verbose_name = _('Image')

    image = models.FileField(upload_to=generate_filename, verbose_name=_('Image'))


class Video(ItemBase):
    class Meta:
        verbose_name_plural = _('Video')
        verbose_name = _('Video')

    url = models.URLField(verbose_name=_('Url'))


class Quiz(ItemBase):
    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    course = models.ForeignKey(verbose_name='Course', to='Course', related_name='quizzes', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(
        blank=True, verbose_name=_("Description"),
        help_text=_("a description of the quiz"))
    slug = models.SlugField(
        max_length=60, blank=False,
        verbose_name=_("SLUG"))
    theme = models.ForeignKey(
        to="themes.Theme", null=True, blank=True,
        on_delete=models.SET_NULL, verbose_name=_("Theme"))
    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."))
    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=_("Correct answer is NOT shown after question."
                    " Answers displayed at the end."),
        verbose_name=_("Answers at end"))
    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, only one attempt by"
                    " a user will be permitted."),
        verbose_name=_("Single Attempt"))
    max_attempts = models.PositiveSmallIntegerField(
        blank=True, null=True, default=2,
        verbose_name=_('Max attempts'),
        help_text=_('Number of attempts available to pass'))
    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        verbose_name=_("Pass Mark"),
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)])
    success_text = models.TextField(
        blank=True, help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"))
    fail_text = models.TextField(
        verbose_name=_("Fail Text"),
        blank=True, help_text=_("Displayed if user fails."))
    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed"
                    " in the quiz list and can only be"
                    " taken by users who can edit"
                    " quizzes."))

    time_limit = models.PositiveIntegerField(
        null=True, blank=True,
        verbose_name=_('Time limit'),
        help_text=_('Time limit from starting of quiz in minutes')
    )
    start_at = models.DateTimeField(
        blank=True, null=True,
        verbose_name=_('Start DateTime'),
        help_text=_('Open access for quiz in show datetime'))
    end_at = models.DateTimeField(
        blank=True, null=True,
        verbose_name=_('End DateTime'),
        help_text=_('Close access for quiz in given datetime'))

    def get_questions(self):
        return self.question.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    @property
    def get_attempts_count(self):
        if self.max_attempts == 1:
            return _(f'{self.max_attempts} time')
        return _(f'{self.max_attempts} times')

    def get_absolute_url(self):
        return reverse('quiz_start', kwargs={'slug': self.slug})

courses/forms.py
from django.forms.models import inlineformset_factory

from question_bank.models import QuestionBank
from .models import Course, Module, Quiz
from django import forms


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        exclude = ['owner',
                   'order',
                   'created_at',
                   'updated_at']

    question_banks = forms.ModelMultipleChoiceField(queryset=QuestionBank.objects.filter(is_active=True),
                                                    required=False)

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            initial = kwargs.setdefault('initial', {})
            initial['question_banks'] = [t.pk for t in kwargs['instance'].question_banks.filter(is_active=True)]

        forms.ModelForm.__init__(self, *args,    **kwargs)
        self.fields['start_at'].widget = forms.DateTimeInput(attrs={
            'placeholder': 'yyyy-mm-dd hh:mm:ss'
        })
        self.fields['end_at'].widget = forms.DateTimeInput(attrs={
            'placeholder': 'yyyy-mm-dd hh:mm:ss'
        })

    def save(self, commit=True):
        instance = forms.ModelForm.save(self, False)

        old_save_m2m = self.save_m2m

        def save_m2m():
            old_save_m2m()
            instance.question_banks.clear()
            instance.question_banks.add(*self.cleaned_data['question_banks'])

        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance


ModuleFormSet = inlineformset_factory(Course,
                                      Module,
                                      fields=['title', 'description'],
                                      extra=1,
                                      can_delete=True)

templates/courses/course/detail.html
{% extends 'base.html' %}
{% load widget_tweaks static %}

{% block style %}
    <style>
        .card-header .fa {
            transition: .3s transform ease-in-out;
        }

        .card-header .collapsed .fa {
            transform: rotate(90deg);
        }

        .card-header {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">

        <!-- Lesson Detail -->
        <div class="row">
            <div class="col-lg-8 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Lesson Description</h6>
                    </div>
                    <div class="card-body">
                        {% if object.image %}
                            <div class="text-center">
                                <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                                     src="{{ object.image.url }}" alt="">
                            </div>
                        {% endif %}
                        <p>{{ object.description }}</p>
                    </div>
                </div>

                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Detail</h6>
                    </div>

                    <div class="card-body">
                        {% if request.user in object.students.all %}
                            <form action="" method="post" id="un-enroll-form">
                                {% csrf_token %}
                                <div id="enrollment-body"></div>
                                <button type="submit" class="btn btn-secondary btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-arrow-left"></i>
                                    </span>
                                    <span class="text">Un enroll now</span>
                                </button>
                            </form>
                        {% else %}
                            <form action="" method="post" id="enroll-form">
                                {% csrf_token %}
                                <div id="enrollment-body">
                                    {% if enroll_form.enrollment_key.errors %}
                                        {% for error in enroll_form.enrollment_key.errors %}
                                            <div class="invalid-feedback">
                                                <label class="text-danger">{{ error }}</label>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    {% render_field enroll_form.enrollment_key class+="form-control form-control-user" placeholder="Enrollment key" %}
                                </div>

                                <div class="my-2"></div>
                                <button type="submit" class="btn btn-light btn-icon-split">
                                    <span class="icon text-gray-600">
                                        <i class="fas fa-arrow-right"></i>
                                    </span>
                                    <span class="text">Enroll now</span>
                                </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">About Supervisor</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">

                            <div class="col-lg-6 col-xs-12 col-sm-12 text-center">
                                <img class="img-profile rounded-circle"
                                     style="height: 100%; width: 100%; display: block;"
                                     src="{% if object.owner.avatar %}{{ object.owner.avatar.url }}{% else %}{% static 'img/avatardefault_92824.png' %}{% endif %}">
                            </div>
                            <div class="col-lg-6 col-sm-12 col-md-12">
                                {% if object.owner.full_name %}
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        Name and Surname
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        {{ object.owner.full_name }}
                                    </div>
                                {% endif %}
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Email
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    {{ object.owner.email }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}


{% block scripts %}
{#    <script>#}
{#        $(document).ready(() => {#}
{#            $('#enroll-form').on('submit', function (e) {#}
{#                e.preventDefault();#}
{##}
{#                let additional_form = $('#enrollment-body');#}
{#                let token = '{{ csrf_token }}';#}
{#                let course = '{{ object.pk }}';#}
{#                let enrollment_key = $('#id_enrollment_key').val();#}
{##}
{#                let data = {#}
{#                    'course': course,#}
{#                    'enrollment_key': enrollment_key,#}
{#                };#}
{##}
{#                $.ajax({#}
{#                    type: "POST",#}
{#                    headers: {"X-CSRFToken": token},#}
{#                    url: "{% url 'enroll_to_course' %}",#}
{#                    data: data,#}
{##}
{#                    success: function (response) {#}
{#                        if (!response.success) {#}
{#                            additional_form.children().remove();#}
{#                            additional_form.append(response.form)#}
{#                        } else if (response.success) {#}
{#                            window.location.replace("{% url 'student_course_detail' object.pk %}");#}
{#                        }#}
{#                    },#}
{#                    error: function (request, errThrown, errObject) {#}
{#                        console.error(request, errThrown, errObject);#}
{#                    }#}
{#                })#}
{#            })#}
{#        });#}
{#    </script>#}

    <script>
        $(document).ready(() => {
            function enrollCourse() {
                $('#enroll-form').on('submit', function (e) {
                e.preventDefault();

                let additional_form = $('#enrollment-body');
                let token = '{{ csrf_token }}';
                let course = '{{ object.pk }}';
                let enrollment_key = $('#id_enrollment_key').val();

                let data = {
                    'course': course,
                    'enrollment_key': enrollment_key,
                };

                $.ajax({
                    type: "POST",
                    headers: {"X-CSRFToken": token},
                    url: "{% url 'enroll_to_course' %}",
                    data: data,

                    success: function (response) {
                        if (!response.success) {
                            console.log(response);
                            additional_form.children().remove();
                            additional_form.append(response.form)
                        } else if (response.success) {
                            window.location.replace("{% url 'student_course_detail' object.pk %}");
                        }
                    },
                    error: function (request, errThrown, errObject) {
                        console.error(request, errThrown, errObject);
                    }
                })
            })
            }

            function unEnrollCourse() {
                $('#un-enroll-form').on('submit', function (e) {
                    e.preventDefault();

                    let additional_form = $('#enrollment-body');
                    let token = '{{ csrf_token }}';
                    let course = '{{ object.pk }}';

                    let data = {
                        'course': course,
                    };

                    $.ajax({
                        type: "POST",
                        headers: {"X-CSRFToken": token},
                        url: "{% url 'un_enroll_from_course' %}",
                        data: data,

                        success: function (response) {
                            if (!response.success) {
                                console.log(response.success)
                            } else if (response.success) {
                                location.reload();
                            }
                        },
                        error: function (request, errThrown, errObject) {
                            console.error(request, errThrown, errObject);
                        }
                    })
                })
            }

            enrollCourse();
            unEnrollCourse();
        });

    </script>

    <script>
        $('.panel-collapse').on('show.bs.collapse', function () {
            $(this).siblings('.panel-heading').addClass('active');
        });

        $('.panel-collapse').on('hide.bs.collapse', function () {
            $(this).siblings('.panel-heading').removeClass('active');
        });
    </script>
{% endblock %}

templates/courses/course/list.html
{% extends 'base.html' %}


{% block content %}

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        {% include 'courses/course/componets/courses.html' %}
    </div>


{%  endblock %}